### ISSUE TITLE
envplugin for setting logging, reload and hmr

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-loader#15]
Maybe we should use this:
http://fuse-box.org/#envplugin

For setting these:
```
(<any>window).FUSEBOX_AURELIA_LOADER_LOGGING = true; // activate logging (when aurelia developmentLogging is used)
(<any>window).FUSEBOX_AURELIA_LOADER_HMR = true; // activate hot reload (need aurelia-hot-module-reload to work)
(<any>window).FUSEBOX_AURELIA_LOADER_RELOAD = true; // just reload document on fusebox hrm event (file change)
```

Could have been like this:

```
fb.EnvPlugin({ 
       FB_AU_LOG: true,
       FB_AU_HMR: false,
       FB_AU_RELOAD: true 
})
```

That way you its easier to set when building

what do you think @arjendeblok @Thanood

**Comment by arjendeblok** [comment]
@vegarringdal Looks fine to me

**Comment by arjendeblok** [comment]
@vegarringdal Please do that. You do not want to set debug information in your code.
If you can change that then I will change the aurelia-seed to use that construct.

**Comment by vegarringdal** [comment]
@arjendeblok fixed, also updated the readme file with some notes about this, and that cache needs to be set to true for HMR to work

**Comment by vegarringdal** [comment]
Made it so both ways work, that way we dont break it for others
