### ISSUE TITLE
Uncaught ReferenceError: define is not defined(...)

### ISSUE THREAD

**Issue by blackgwe** [fuse-box/fuse-box-aurelia-loader#25]
Hi!
fuse-box-aurelia-seed throws an errow "define is not defined" - suppose a bug here because it's only a few modules changed....

------------------------Browser Log ------------------------------------------------
connect ws://localhost:7775
connecting...
Uncaught ReferenceError: define is not defined(…)
------------------------------Shell ----------------------------------------------------
npm run start                                                                                                                                       

> fuse-box-aurelia-seed@0.0.2 start /tmp/fuse-box-aurelia-seed
> npm run build-dev

> fuse-box-aurelia-seed@0.0.2 build-dev /tmp/fuse-box-aurelia-seed
> node ./build/fb-app-build-bundle-dev

  → WARNING sourceMap is deprecated. Use { sourcemaps : true } instead
21:00:48 : Launching dev server on port 7775
  → Typescript config:  /tsconfig.json

└── default (12 files,  28.7 kB)
      main.js
      app.js
      misc/blur-image.js
      routes/child-router.js
      routes/users.js
      routes/welcome.js
      app.html
      components/nav-bar.html
      routes/child-router.html
      routes/users.html
      routes/welcome.html
      styles/styles.css
└── jquery (1 files) 203 Bytes
└── fusebox-hot-reload (1 files) 1.8 kB
└── fusebox-websocket (1 files) 2.8 kB
└── events (1 files) 9.8 kB
└── aurelia-pal (1 files) 2.7 kB
└── aurelia-pal-browser (1 files) 14.9 kB
└── aurelia-framework (1 files) 16.7 kB
└── aurelia-dependency-injection (1 files) 22.3 kB
└── aurelia-metadata (1 files) 7.3 kB
└── aurelia-binding (1 files) 168.4 kB
└── aurelia-logging (1 files) 2.3 kB
└── aurelia-task-queue (1 files) 5.4 kB
└── default (12 files,  28.7 kB)
      main.js
      app.js
      misc/blur-image.js
      routes/child-router.js
      routes/users.js
      routes/welcome.js
      app.html
      components/nav-bar.html
      routes/child-router.html
      routes/users.html
      routes/welcome.html
      styles/styles.css
└── jquery (1 files) 203 Bytes
└── fusebox-hot-reload (1 files) 1.8 kB
└── fusebox-websocket (1 files) 2.8 kB
└── events (1 files) 9.8 kB
└── aurelia-pal (1 files) 2.7 kB
└── aurelia-pal-browser (1 files) 14.9 kB
└── aurelia-framework (1 files) 16.7 kB
└── aurelia-dependency-injection (1 files) 22.3 kB
└── aurelia-metadata (1 files) 7.3 kB
└── aurelia-binding (1 files) 168.4 kB
└── aurelia-logging (1 files) 2.3 kB
└── aurelia-task-queue (1 files) 5.4 kB
└── aurelia-templating (1 files) 147.7 kB
└── aurelia-path (1 files) 5.7 kB
└── aurelia-loader (1 files) 4.7 kB
└── aurelia-logging-console (1 files) 1.9 kB
└── aurelia-templating-binding (1 files) 25.1 kB
└── aurelia-templating-resources (32 files) 81.3 kB
└── aurelia-event-aggregator (1 files) 3.6 kB
└── aurelia-history-browser (1 files) 9.4 kB
└── aurelia-history (1 files) 1 kB
└── aurelia-templating-router (4 files) 15.6 kB
└── aurelia-router (1 files) 54.5 kB
└── aurelia-route-recognizer (1 files) 12.8 kB

    Bundle
    Size: 646.6 kB 
    Time: 13s 294ms
21:01:01 : HMR is enabled
21:01:01 : Client connected
21:01:05 : Connection closed
21:01:05 : Client connected

**Comment by vegarringdal** [comment]
if you are on fusebox 124, check your tsconfig that your module is set to commonjs, that one got me earlier today

**Comment by vegarringdal** [comment]
I just tested the seed, its working fine now, but wee need to update it more, since sourcemap part is wrong at it takes like forever to build something that should take 1-2 sec. (sorry about that)

**Comment by blackgwe** [comment]
THANK you VERY MUCH!!
