### ISSUE TITLE
The loader should be transpiled to es5

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box-aurelia-loader#3]
subj

**Comment by vegarringdal** [comment]
Running ```gulp build```
Creates a commonjs/es5 under:
https://github.com/fuse-box/fuse-box-aurelia-loader/tree/master/dist/commonjs

This is doing it:
https://github.com/fuse-box/fuse-box-aurelia-loader/blob/master/build/build.js#L15-L20

Or did you think about somthing else ?

**Comment by nchanged** [comment]
Great! Sorry, just want to make sure if. I think we need to make a fusebox bundle instead =) It's more efficient. Then we can require it in the aurelia project.

**Comment by vegarringdal** [comment]
unsure where you are going with that, but so much I dont know about bundling/bundles etc etc. :smile:

can you explain more ?

**Comment by nchanged** [comment]
I wanted to have a fusebox bundle published =) But that will work as well, no worries!

**Comment by vegarringdal** [comment]
Agree we should replace it, tslint is that supported out of the box, its kinda important.
Been tricked in my sample app by it not telling me about errors, had silence errors somehow, no errors in console in chrome weird enough
