### ISSUE TITLE
rollup/quantum/code splitting

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-loader#30]
@nchanged 
Is there any way to get these features working with fusebox when we have the fusebox-aurelia-loader that everything needs to go through ?

Features:
* rollup (http://fuse-box.org/page/rollup)
* quantum (http://fuse-box.org/page/quantum)
* code splitting (http://fuse-box.org/page/code-splitting)

You been improving fusebox a lot lately, so dunno if anything have changed ?

**Comment by nchanged** [comment]
Ok, 
* rollup has been removed in 3.0 branch already ;-) We should all use Quantum instead
* we can do that
* if we can do ^2 then we can do code splitting too

**Comment by vegarringdal** [comment]
@nchanged 

Very nice
Do you need me to change parts of the loader for this to work, or do we just need you to create the module map you told me about earlier.
Anything else ?

**Comment by nchanged** [comment]
I will start rolling betas for 3.0 soon, and i will let you know ;-)
