### ISSUE TITLE
init-> package "xxxx" not working as excpected

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-loader#5]
@nchanged @devmondo 

I need some help here, because there is something Im not understanding, and its kinda stopping my progress

In the code under Im trying to make a basic package of the loader with all the aurelia libs needed
But for some reason it will not have entry point

![image](https://cloud.githubusercontent.com/assets/2901416/23039207/1dfbd114-f48d-11e6-9c32-06817de07763.png)

Ive tried with and without globals... is this a bug ?

```
let fuseLoader = fuse.init({
        package:"fuse-box-aurelia-loader",
        homeDir: "../src",
        outFile: "./bundle/fusebox-aurelia-bundle.js",
        globals:{"fuse-box-aurelia-loader":"fuse-box-aurelia-loader"},
        plugins: [
            fb.CSSPlugin(),
            fb.HTMLPlugin(),
            fb.TypeScriptHelpers()
    ]
})

fuseLoader.bundle(`>index.ts
    + aurelia-bootstrapper
    + aurelia-framework
    + aurelia-pal
    + aurelia-metadata
    + aurelia-loader-default
    + aurelia-polyfills
    + aurelia-fetch-client
    + aurelia-pal-browser
    + aurelia-animator-css
    + aurelia-logging-console 
    + aurelia-templating-binding 
    + aurelia-templating-resources 
    + aurelia-event-aggregator 
    + aurelia-history-browser 
    + aurelia-templating-router`
    );
```

**Comment by nchanged** [comment]
Are you loading that one in another bundle? If yes, https://github.com/fuse-box/fuse-box/issues/188
this will be released very soon and should fix it all!

**Comment by vegarringdal** [comment]
No

Im running this for the dev server

```javascript
let appBundle = fuse.init({
    homeDir: "./src",
    outFile: "./bundle/app-bundle.js",
    useCache:false,
    plugins: [
        fb.CSSPlugin(),
        fb.HTMLPlugin({ useDefault: true }),
        fb.TypeScriptHelpers()
    ],
    sourceMap: {
        bundleReference: "./bundle/app-bundle.js.map",
        outFile: "./bundle/app-bundle.js.map",
    }
});


// Start dev server
appBundle.devServer(`
    > [main.ts]
    + [**/*.html] 
    + [**/*.ts] 
    + [**/*.css]
    `,{
   root: './'
})
```

But as you can see Ive lot loaded that separate bundle, so thats why Im asking if its a bug :-)
Or if its me just doing something wrong 

![image](https://cloud.githubusercontent.com/assets/2901416/23040110/5b6b3f6e-f490-11e6-8f81-980210cdf0fc.png)

**Comment by nchanged** [comment]
Ok.. not sure i got you
Have you tried
```
FuseBox.import("fuse-box-aurelia-loader")
```
in the console?

**Comment by vegarringdal** [comment]
yes :-)

Ive pretty much tried everything

![image](https://cloud.githubusercontent.com/assets/2901416/23040661/6e83c100-f492-11e6-98b3-e172d151b521.png)


atm I will hack it... :-)
We can look more into this when Ive updated the sample, then you can look at code, better you spend time on the "addPackage" and bugs 
```
//hack for now..
FuseBox.pkg("fuse-box-aurelia-loader", {}, function(___scope___) {
        ___scope___.entry = "index.js"
});
```

**Comment by nchanged** [comment]
Can you update fuse-box?

**Comment by nchanged** [comment]
If nothing helps, that's a bug. If you could write some steps, what to clone, what to run, and where to look =) I would appreciate that.

**Comment by vegarringdal** [comment]
using 1.3.116 now, deleted cache, same issue
Even tried with and without: globals:{"fuse-box-aurelia-loader":"fuse-box-aurelia-loader"}, and deleted cache folder between.

Ill clean up the sample part Im working on, then I can more easily show you what/where :-)

**Comment by nchanged** [comment]
Sure! Thanks a lot!

**Comment by vegarringdal** [comment]
@nchanged 
Updated and cleaned up sample
So now its ready for you to see if its a bug or not

1:
```git clone https://github.com/fuse-box/fuse-box-aurelia-loader```

2: 
```cd fuse-box-aurelia-loader/sample```

3:
```npm install```

4:
Set breakpoint here
https://github.com/fuse-box/fuse-box-aurelia-loader/blob/master/sample/src/main.ts#L4
Its really just to uncomment the "debugger" statement

5:
Build it
```npm run build-all```
You have to be in sample catalog

6:
Open app in broser, when it hits breakpoint you will se that entry is missing in the loader

![image](https://cloud.githubusercontent.com/assets/2901416/23044397/5318ccc2-f4a0-11e6-93ad-9a86b6fc9737.png)

**Comment by nchanged** [comment]
I will try that tomorrow! Could you create an issue in fuse-box referencing this one, so I won't forget?
Thanks for the great job you are doing here! 🔥

**Comment by vegarringdal** [comment]
sure 👍 

Will that part with addPackage be on the roadmap in the near future?

**Comment by nchanged** [comment]
at https://github.com/fuse-box/fuse-box/issues/194

**Comment by nchanged** [comment]
@vegarringdal absolutely! Just a couple releases with critical fixes, and then we get to the features!! yum!

**Comment by vegarringdal** [comment]
Great, keep up the good work, fusebox is a lot more fun then any other bundling Ive been doing, but havent really been doing any... was so boring 😂
