### ISSUE TITLE
Aurelia-skelton-fusebox

### ISSUE THREAD

**Issue by vegarringdal** [fuse-box/fuse-box-aurelia-loader#6]
@nchanged 
Should we build a Aurelia-skelton-fusebox

Kinda like they have here ?
https://github.com/aurelia/skeleton-navigation

Nice way for people to start using/testing it
The sample catalog in this repo will have a lot more to help see bugs etc
It would be more or less copy of what Aurelia have...

**Comment by nchanged** [comment]
Oh you mean seeds, we call it seeds here :) you have an access to one in fusebox btw:)

**Comment by vegarringdal** [comment]
ok, Ill have a look at that later then

**Comment by arjendeblok** [comment]
@nchanged I made a working example based on the https://github.com/aurelia/skeleton-navigation based on the new loader.
You can find it at https://github.com/arjendeblok/fuse-box-aurelia-seed 
If you want I can make a pull request for it.

**Comment by nchanged** [comment]
@arjendeblok thanks a lot! I will take a look a bit later!

**Comment by nchanged** [comment]
And of course! make a PR! I would appreciate that!

**Comment by vegarringdal** [comment]
@arjendeblok Great :-)

**Comment by vegarringdal** [comment]
@arjendeblok 
Ill fork you version so I can try it 👍

**Comment by arjendeblok** [comment]
Made a pull request at https://github.com/fuse-box/fuse-box-aurelia-seed.
